apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
      path: "/run/desktop/mnt/host/c/Users/Szymon/OneDrive/Pulpit/2rok4sem/TechnologieChmurowe/Technologie-Chmurowe/projekt/tmp"
  claimRef:
      name: mongo
