version: '3'

services:

  api:
    build:
      dockerfile: dockerfile.dev
      context: ./backend
    depends_on:
      - cache
    environment: 
      PGPORT: 5000
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: redispass
    ports: 
      - 5000:5000

  cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass redispass
    volumes: 
      - cache:/data

  client:
    stdin_open: true
    build: 
      context: ./fronted
      dockerfile: dockerfile.dev
    volumes:
      - '/app/node_modules'
      - './client:/app'
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: dockerfile
      context: ./nginx
    ports:
      - "3050:80"
volumes:
  cache:
    driver: local