version: '3'

services:

  api:
    build:
      dockerfile: dockerfile.dev
      context: ./backend
    depends_on:
      - cache
    environment: 
      PGPORT: 5000
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: redispass
      CHOKIDAR_USEPOLLING: "true"
    ports: 
      - 5000:5000
    volumes:
      - /app/node_modules
      - ./backend/src:/app/src

  cache:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass redispass
    volumes: 
      - cache:/data

  client:
    build: 
      context: ./client
      dockerfile: dockerfile.dev
    restart: always
    environment:
        CHOKIDAR_USEPOLLING: true
        FAST_REFRESH: false
        NODE_ENV: development
    volumes:
      - /app/node_modules
      - .\client\src:/app/src
    ports:
      - 3000:3000
    
  nginx:
    build:
      dockerfile: dockerfile
      context: ./nginx
    depends_on:
      - api
      - client
    restart: always
    ports:
      - 80:80

volumes:
  cache:
    driver: local
