apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data 
  labels:
    type: local
    app: demo
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/volume"